import { Container, Header } from "@/shared/components/shared";
import { Suspense } from "react";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function CheckoutLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<main className="min-h-screen bg-[#f3f1ed]">
			<Container>
				<Suspense>
					<Header
						className="border-gray-200"
						hasSearch={false}
						hasCart={false}
					/>
				</Suspense>
				{children}
			</Container>
		</main>
	);
}
